[package]
name = "xchacha20_encryption_app"
version = "0.1.0"
edition = "2021"

[dependencies]
chacha20poly1305 = "^0.10.1"
rand = "^0.8.5"
clap = { version = "^4.5.20", features = ["derive"] }
anyhow = "^1.0.71"
zeroize = "^1.5.6"  # Added for zeroizing sensitive data
