[package]
name = "crypt"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
rand = "0.8.5"
rand_chacha = "0.3.1"
argon2 = "0.5.3"
aes = "0.8.4"
ctr = "0.9.2"
zeroize = "1.8.1"
sha2 = "0.10.8"